export interface Product {
  id: number;
  name: string;
  price: number;
  discount?: number;
  badge?: string;
  category: string;
  brand: string;
  image?: string;
  images?: string[];
  rating?: number;
  reviews?: number;
  description?: string;
  fullDescription?: string;
  characteristics?: { label: string; value: string }[];
  usage?: string;
  inStock?: boolean;
  sku?: string;
}

export interface Review {
  id: number;
  productId: number;
  userName: string;
  rating: number;
  date: string;
  comment: string;
  helpful?: number;
}

export const CATEGORIES = [
  { id: 'zdravje', name: 'Здравје', count: 374, icon: '💊' },
  { id: 'vitamini', name: 'Витамини', count: 156, icon: '🍊' },
  { id: 'kozmetika', name: 'Козметика', count: 289, icon: '✨' },
  { id: 'majka-dete', name: 'Мајка и Дете', count: 112, icon: '👶' },
  { id: 'herbali', name: 'Хербали', count: 98, icon: '🌿' },
  { id: 'oralna-higiena', name: 'Орална хигиена', count: 45, icon: '🦷' },
];

export const BRANDS = [
  'Solgar',
  'Now Foods',
  'Nature Made',
  'Centrum',
  'Vichy',
  'La Roche-Posay',
  'Eucerin',
  'Bioderma',
  'A-Derma',
  'Sensodyne',
];

export const PRODUCTS: Product[] = [
  // Vitamini
  {
    id: 1,
    name: 'Витамин Ц 1000mg',
    price: 450,
    discount: 20,
    badge: 'На попуст',
    category: 'vitamini',
    brand: 'Solgar',
    rating: 4.8,
    reviews: 124,
    sku: 'SOL-VC1000',
    inStock: true,
    description: 'Витамин Ц во висока доза од 1000mg за поддршка на имунитетот и антиоксидативна заштита.',
    fullDescription: 'Solgar Витамин Ц 1000mg е премиум додаток на исхраната кој обезбедува висока доза на аскорбинска киселина. Витамин Ц е есенцијален нутриент кој телото не може само да го произведе, а е клучен за многу биолошки функции. Помага во синтезата на колаген, ја подобрува апсорпцијата на железо и делува како моќен антиоксидант. Овој производ е идеален за лица кои сакаат да го зајакнат имунитетот, особено во зимскиот период.',
    characteristics: [
      { label: 'Активна супстанца', value: 'Аскорбинска киселина 1000mg' },
      { label: 'Форма', value: 'Таблети' },
      { label: 'Количина', value: '100 таблети' },
      { label: 'Дозирање', value: '1 таблета дневно' },
      { label: 'Вегански', value: 'Да' },
      { label: 'Без глутен', value: 'Да' },
    ],
    usage: 'Земајте 1 таблета дневно со оброк. Не надминувајте ја препорачаната доза. Чувајте на суво место на собна температура.',
  },
  {
    id: 2,
    name: 'Магнезиум + Б6',
    price: 320,
    badge: 'Ново',
    category: 'vitamini',
    brand: 'Now Foods',
    rating: 4.5,
    reviews: 89,
    sku: 'NF-MGB6',
    inStock: true,
    description: 'Комбинација на магнезиум и витамин Б6 за намалување на замор и поддршка на нервниот систем.',
    fullDescription: 'Now Foods Магнезиум + Б6 е синергистичка формула која комбинира магнезиум цитрат со витамин Б6 за оптимална апсорпција и ефикасност. Магнезиумот учествува во над 300 ензимски реакции во телото и е клучен за мускулната функција, енергетскиот метаболизам и нервниот систем. Витамин Б6 ја подобрува апсорпцијата на магнезиумот.',
    characteristics: [
      { label: 'Магнезиум', value: '400mg (Магнезиум цитрат)' },
      { label: 'Витамин Б6', value: '25mg' },
      { label: 'Форма', value: 'Капсули' },
      { label: 'Количина', value: '90 капсули' },
      { label: 'Дозирање', value: '2 капсули дневно' },
    ],
    usage: 'Земајте 2 капсули дневно со храна. Препорачливо е да се земе навечер за подобар сон.',
  },
  {
    id: 3,
    name: 'Витамин D3 2000IU',
    price: 280,
    category: 'vitamini',
    brand: 'Nature Made',
    rating: 4.7,
    reviews: 156,
    sku: 'NM-VD32000',
    inStock: true,
    description: 'Витамин D3 за здрави коски, заби и поддршка на имунитетот.',
    fullDescription: 'Nature Made Витамин D3 2000IU обезбедува оптимална доза на витамин D во најактивната форма D3 (холекалциферол). Овој витамин е есенцијален за апсорпција на калциум и фосфор, одржување на здрави коски и заби, и нормална функција на имунитетот. Посебно е важен во зимските месеци кога изложеноста на сонце е намалена.',
    characteristics: [
      { label: 'Активна супстанца', value: 'Холекалциферол 2000IU' },
      { label: 'Форма', value: 'Меки капсули' },
      { label: 'Количина', value: '120 капсули' },
      { label: 'Дозирање', value: '1 капсула дневно' },
    ],
    usage: 'Земајте 1 капсула дневно со оброк богат со масти за подобра апсорпција.',
  },
  {
    id: 4,
    name: 'Калциум + Витамин D',
    price: 380,
    discount: 25,
    badge: 'На попуст',
    category: 'vitamini',
    brand: 'Centrum',
    rating: 4.6,
    reviews: 78,
    sku: 'CEN-CALVD',
    inStock: true,
    description: 'Комплетна формула за здрави коски со калциум и витамин D.',
    fullDescription: 'Centrum Калциум + Витамин D е специјално дизајнирана формула за поддршка на коскената густина и здравјето на зглобовите. Калциумот е најважниот минерал за коските, а витамин D е неопходен за неговата апсорпција. Оваа комбинација е идеална за жени во менопауза, постари лица и сите кои сакаат да ги зајакнат коските.',
    characteristics: [
      { label: 'Калциум', value: '600mg (Калциум карбонат)' },
      { label: 'Витамин D3', value: '400IU' },
      { label: 'Форма', value: 'Таблети' },
      { label: 'Количина', value: '60 таблети' },
      { label: 'Дозирање', value: '1 таблета 2 пати дневно' },
    ],
    usage: 'Земајте 1 таблета 2 пати дневно со оброк. Оставете најмалку 4-6 часа меѓу дозите.',
  },
  {
    id: 5,
    name: 'Пробиотици 50 млрд',
    price: 550,
    badge: 'Ново',
    category: 'vitamini',
    brand: 'Now Foods',
    rating: 4.9,
    reviews: 203,
    sku: 'NF-PRO50',
    inStock: true,
    description: 'Моќна пробиотичка формула со 50 милијарди активни култури за здрава дигестија.',
    fullDescription: 'Now Foods Пробиотици 50 млрд содржи 10 различни соеви на корисни бактерии за комплетна поддршка на цревниот микробиом. Оваа формула помага при дигестивни проблеми, јакнење на имунитетот и подобра апсорпција на нутриенти. Капсулите се со одложено ослободување за да ги заштитат бактериите од желудочната киселина.',
    characteristics: [
      { label: 'CFU', value: '50 милијарди' },
      { label: 'Соеви', value: '10 пробиотички соеви' },
      { label: 'Форма', value: 'Капсули со одложено ослободување' },
      { label: 'Количина', value: '30 капсули' },
      { label: 'Складирање', value: 'Чувајте во фрижидер' },
    ],
    usage: 'Земајте 1 капсула дневно на празен стомак, најдобро наутро. Чувајте во фрижидер.',
  },
  {
    id: 6,
    name: 'Омега 3 Fish Oil',
    price: 620,
    discount: 15,
    category: 'vitamini',
    brand: 'Solgar',
    rating: 4.7,
    reviews: 167,
    sku: 'SOL-OM3',
    inStock: true,
    description: 'Премиум рибино масло богато со EPA и DHA за здраво срце и мозок.',
    fullDescription: 'Solgar Омега 3 Fish Oil е добиен од диви риби од длабоки води и е молекуларно дестилиран за да се отстранат тешките метали и загадувачите. Содржи високи концентрации на EPA и DHA, двете најважни омега-3 масни киселини. Овие есенцијални масни киселини се клучни за кардиоваскуларното здравје, когнитивната функција и здравјето на очите.',
    characteristics: [
      { label: 'EPA', value: '360mg по капсула' },
      { label: 'DHA', value: '240mg по капсула' },
      { label: 'Форма', value: 'Меки капсули' },
      { label: 'Количина', value: '100 капсули' },
      { label: 'Извор', value: 'Диви риби од длабоки води' },
    ],
    usage: 'Земајте 2 капсули дневно со оброк. Може да се чува во фрижидер за да се спречи мирис на риба.',
  },
  {
    id: 7,
    name: 'Мултивитамин за жени',
    price: 480,
    category: 'vitamini',
    brand: 'Centrum',
    rating: 4.4,
    reviews: 92,
    sku: 'CEN-MULTW',
    inStock: true,
    description: 'Комплетен мултивитамин специјално формулиран за потребите на жените.',
    fullDescription: 'Centrum Мултивитамин за жени е сеопфатна формула која ги адресира специфичните нутритивни потреби на жените. Содржи зголемени нивоа на железо, калциум и фолна киселина, кои се особено важни за женското здравје. Вклучува и антиоксиданти за здрава кожа и коса.',
    characteristics: [
      { label: 'Витамини', value: '23 витамини и минерали' },
      { label: 'Железо', value: '18mg' },
      { label: 'Калциум', value: '500mg' },
      { label: 'Фолна киселина', value: '400mcg' },
      { label: 'Количина', value: '90 таблети' },
    ],
    usage: 'Земајте 1 таблета дневно со оброк.',
  },
  {
    id: 8,
    name: 'Железо + Фолна киселина',
    price: 290,
    discount: 10,
    category: 'vitamini',
    brand: 'Nature Made',
    rating: 4.3,
    reviews: 45,
    sku: 'NM-IRFOL',
    inStock: false,
    description: 'Есенцијална комбинација за превенција на анемија и поддршка за бремени жени.',
    fullDescription: 'Nature Made Железо + Фолна киселина е формулиран за лица со зголемени потреби од железо, вклучувајќи бремени жени и лица со анемија. Железото е есенцијално за транспорт на кислород во крвта, а фолната киселина е клучна за развој на плодот и создавање на црвени крвни клетки.',
    characteristics: [
      { label: 'Железо', value: '27mg (Железо фумарат)' },
      { label: 'Фолна киселина', value: '400mcg' },
      { label: 'Форма', value: 'Таблети' },
      { label: 'Количина', value: '60 таблети' },
    ],
    usage: 'Земајте 1 таблета дневно на празен стомак со витамин Ц за подобра апсорпција.',
  },
  // Kozmetika
  {
    id: 9,
    name: 'Крем за лице SPF 50',
    price: 890,
    discount: 15,
    category: 'kozmetika',
    brand: 'Vichy',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 10,
    name: 'Хидратантен серум',
    price: 1250,
    badge: 'Ново',
    category: 'kozmetika',
    brand: 'La Roche-Posay',
    rating: 4.9,
    reviews: 178,
  },
  {
    id: 11,
    name: 'Мицеларна вода 400ml',
    price: 420,
    discount: 20,
    badge: 'На попуст',
    category: 'kozmetika',
    brand: 'Bioderma',
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 12,
    name: 'Ноќен крем против брчки',
    price: 1450,
    category: 'kozmetika',
    brand: 'Eucerin',
    rating: 4.6,
    reviews: 98,
  },
  {
    id: 13,
    name: 'Крем за раце',
    price: 280,
    category: 'kozmetika',
    brand: 'A-Derma',
    rating: 4.4,
    reviews: 67,
  },
  {
    id: 14,
    name: 'Шампон против перут',
    price: 520,
    discount: 10,
    category: 'kozmetika',
    brand: 'Vichy',
    rating: 4.5,
    reviews: 143,
  },
  // Zdravje
  {
    id: 15,
    name: 'Маска за лице KN95',
    price: 150,
    category: 'zdravje',
    brand: 'Now Foods',
    rating: 4.2,
    reviews: 89,
  },
  {
    id: 16,
    name: 'Дигитален термометар',
    price: 380,
    discount: 15,
    category: 'zdravje',
    brand: 'Nature Made',
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 17,
    name: 'Крвен притисок монитор',
    price: 2800,
    discount: 20,
    badge: 'На попуст',
    category: 'zdravje',
    brand: 'Centrum',
    rating: 4.8,
    reviews: 78,
  },
  {
    id: 18,
    name: 'Прва помош комплет',
    price: 650,
    category: 'zdravje',
    brand: 'Now Foods',
    rating: 4.5,
    reviews: 45,
  },
  // Herbali
  {
    id: 19,
    name: 'Валеријана капсули',
    price: 320,
    category: 'herbali',
    brand: 'Solgar',
    rating: 4.4,
    reviews: 112,
  },
  {
    id: 20,
    name: 'Ехинацеа екстракт',
    price: 280,
    discount: 10,
    category: 'herbali',
    brand: 'Nature Made',
    rating: 4.5,
    reviews: 89,
  },
  {
    id: 21,
    name: 'Гинко Билоба 120mg',
    price: 450,
    badge: 'Ново',
    category: 'herbali',
    brand: 'Now Foods',
    rating: 4.7,
    reviews: 67,
  },
  {
    id: 22,
    name: 'Куркума + пиперин',
    price: 380,
    discount: 25,
    badge: 'На попуст',
    category: 'herbali',
    brand: 'Solgar',
    rating: 4.8,
    reviews: 198,
  },
  // Oralna higiena
  {
    id: 23,
    name: 'Паста за заби Sensodyne',
    price: 280,
    category: 'oralna-higiena',
    brand: 'Sensodyne',
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 24,
    name: 'Устен раствор антибактериски',
    price: 350,
    discount: 15,
    category: 'oralna-higiena',
    brand: 'Sensodyne',
    rating: 4.4,
    reviews: 112,
  },
];

export const REVIEWS: Review[] = [
  {
    id: 1,
    productId: 1,
    userName: 'Марија С.',
    rating: 5,
    date: '2024-01-15',
    comment: 'Одличен витамин Ц! Го користам веќе неколку месеци и се чувствувам многу подобро. Препорачувам!',
    helpful: 12,
  },
  {
    id: 2,
    productId: 1,
    userName: 'Петар М.',
    rating: 4,
    date: '2024-01-10',
    comment: 'Добар квалитет, но таблетите се малку големи за голтање. Сепак, ефектот е одличен.',
    helpful: 8,
  },
  {
    id: 3,
    productId: 1,
    userName: 'Ана Т.',
    rating: 5,
    date: '2024-01-05',
    comment: 'Solgar е секогаш врвен квалитет. Овој витамин Ц ми помогна да го преминам сезоната на грип без проблеми.',
    helpful: 15,
  },
  {
    id: 4,
    productId: 1,
    userName: 'Иван К.',
    rating: 5,
    date: '2023-12-20',
    comment: 'Најдобар витамин Ц што сум го пробал. Вреди секој денар!',
    helpful: 6,
  },
  {
    id: 5,
    productId: 2,
    userName: 'Елена П.',
    rating: 5,
    date: '2024-01-12',
    comment: 'Магнезиумот ми помогна со мускулните грчеви и подобро спијам навечер. Многу задоволна!',
    helpful: 10,
  },
  {
    id: 6,
    productId: 2,
    userName: 'Стефан Д.',
    rating: 4,
    date: '2024-01-08',
    comment: 'Добар производ, но требаше околу 2 недели да почувствувам разлика.',
    helpful: 5,
  },
  {
    id: 7,
    productId: 5,
    userName: 'Катерина В.',
    rating: 5,
    date: '2024-01-14',
    comment: 'Најдобри пробиотици што сум ги пробала! Дигестијата ми е многу подобра од кога ги земам.',
    helpful: 20,
  },
  {
    id: 8,
    productId: 5,
    userName: 'Горан Н.',
    rating: 5,
    date: '2024-01-11',
    comment: 'Препорака од гастроентеролог. Резултатите се видливи веќе по првата недела.',
    helpful: 18,
  },
];
