export interface Product {
  id: number;
  name: string;
  price: number;
  discount?: number;
  badge?: string;
  category: string;
  brand: string;
  image?: string;
  rating?: number;
  reviews?: number;
}

export const CATEGORIES = [
  { id: 'zdravje', name: 'Здравје', count: 374, icon: '💊' },
  { id: 'vitamini', name: 'Витамини', count: 156, icon: '🍊' },
  { id: 'kozmetika', name: 'Козметика', count: 289, icon: '✨' },
  { id: 'majka-dete', name: 'Мајка и Дете', count: 112, icon: '👶' },
  { id: 'herbali', name: 'Хербали', count: 98, icon: '🌿' },
  { id: 'oralna-higiena', name: 'Орална хигиена', count: 45, icon: '🦷' },
];

export const BRANDS = [
  'Solgar',
  'Now Foods',
  'Nature Made',
  'Centrum',
  'Vichy',
  'La Roche-Posay',
  'Eucerin',
  'Bioderma',
  'A-Derma',
  'Sensodyne',
];

export const PRODUCTS: Product[] = [
  // Vitamini
  {
    id: 1,
    name: 'Витамин Ц 1000mg',
    price: 450,
    discount: 20,
    badge: 'На попуст',
    category: 'vitamini',
    brand: 'Solgar',
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: 'Магнезиум + Б6',
    price: 320,
    discount: 0,
    badge: 'Ново',
    category: 'vitamini',
    brand: 'Now Foods',
    rating: 4.5,
    reviews: 89,
  },
  {
    id: 3,
    name: 'Витамин D3 2000IU',
    price: 280,
    discount: 0,
    category: 'vitamini',
    brand: 'Nature Made',
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 4,
    name: 'Калциум + Витамин D',
    price: 380,
    discount: 25,
    badge: 'На попуст',
    category: 'vitamini',
    brand: 'Centrum',
    rating: 4.6,
    reviews: 78,
  },
  {
    id: 5,
    name: 'Пробиотици 50 млрд',
    price: 550,
    discount: 0,
    badge: 'Ново',
    category: 'vitamini',
    brand: 'Now Foods',
    rating: 4.9,
    reviews: 203,
  },
  {
    id: 6,
    name: 'Омега 3 Fish Oil',
    price: 620,
    discount: 15,
    category: 'vitamini',
    brand: 'Solgar',
    rating: 4.7,
    reviews: 167,
  },
  {
    id: 7,
    name: 'Мултивитамин за жени',
    price: 480,
    discount: 0,
    category: 'vitamini',
    brand: 'Centrum',
    rating: 4.4,
    reviews: 92,
  },
  {
    id: 8,
    name: 'Железо + Фолна киселина',
    price: 290,
    discount: 10,
    category: 'vitamini',
    brand: 'Nature Made',
    rating: 4.3,
    reviews: 45,
  },
  // Kozmetika
  {
    id: 9,
    name: 'Крем за лице SPF 50',
    price: 890,
    discount: 15,
    category: 'kozmetika',
    brand: 'Vichy',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 10,
    name: 'Хидратантен серум',
    price: 1250,
    discount: 0,
    badge: 'Ново',
    category: 'kozmetika',
    brand: 'La Roche-Posay',
    rating: 4.9,
    reviews: 178,
  },
  {
    id: 11,
    name: 'Мицеларна вода 400ml',
    price: 420,
    discount: 20,
    badge: 'На попуст',
    category: 'kozmetika',
    brand: 'Bioderma',
    rating: 4.7,
    reviews: 312,
  },
  {
    id: 12,
    name: 'Ноќен крем против брчки',
    price: 1450,
    discount: 0,
    category: 'kozmetika',
    brand: 'Eucerin',
    rating: 4.6,
    reviews: 98,
  },
  {
    id: 13,
    name: 'Крем за раце',
    price: 280,
    discount: 0,
    category: 'kozmetika',
    brand: 'A-Derma',
    rating: 4.4,
    reviews: 67,
  },
  {
    id: 14,
    name: 'Шампон против перут',
    price: 520,
    discount: 10,
    category: 'kozmetika',
    brand: 'Vichy',
    rating: 4.5,
    reviews: 143,
  },
  // Zdravje
  {
    id: 15,
    name: 'Маска за лице KN95',
    price: 150,
    discount: 0,
    category: 'zdravje',
    brand: 'Now Foods',
    rating: 4.2,
    reviews: 89,
  },
  {
    id: 16,
    name: 'Дигитален термометар',
    price: 380,
    discount: 15,
    category: 'zdravje',
    brand: 'Nature Made',
    rating: 4.6,
    reviews: 156,
  },
  {
    id: 17,
    name: 'Крвен притисок монитор',
    price: 2800,
    discount: 20,
    badge: 'На попуст',
    category: 'zdravje',
    brand: 'Centrum',
    rating: 4.8,
    reviews: 78,
  },
  {
    id: 18,
    name: 'Прва помош комплет',
    price: 650,
    discount: 0,
    category: 'zdravje',
    brand: 'Now Foods',
    rating: 4.5,
    reviews: 45,
  },
  // Herbali
  {
    id: 19,
    name: 'Валеријана капсули',
    price: 320,
    discount: 0,
    category: 'herbali',
    brand: 'Solgar',
    rating: 4.4,
    reviews: 112,
  },
  {
    id: 20,
    name: 'Ехинацеа екстракт',
    price: 280,
    discount: 10,
    category: 'herbali',
    brand: 'Nature Made',
    rating: 4.5,
    reviews: 89,
  },
  {
    id: 21,
    name: 'Гинко Билоба 120mg',
    price: 450,
    discount: 0,
    badge: 'Ново',
    category: 'herbali',
    brand: 'Now Foods',
    rating: 4.7,
    reviews: 67,
  },
  {
    id: 22,
    name: 'Куркума + пиперин',
    price: 380,
    discount: 25,
    badge: 'На попуст',
    category: 'herbali',
    brand: 'Solgar',
    rating: 4.8,
    reviews: 198,
  },
  // Oralna higiena
  {
    id: 23,
    name: 'Паста за заби Sensodyne',
    price: 280,
    discount: 0,
    category: 'oralna-higiena',
    brand: 'Sensodyne',
    rating: 4.6,
    reviews: 234,
  },
  {
    id: 24,
    name: 'Устен раствор антибактериски',
    price: 350,
    discount: 15,
    category: 'oralna-higiena',
    brand: 'Sensodyne',
    rating: 4.4,
    reviews: 112,
  },
];
